server:
  host: 0.0.0.0
  port: 8004
  reload: true
  allow_origins:
    - "*"
  enable_web_ui: true

storage:
  - name: default
    type: disk
    path: ./data/default/

database:
  url: sqlite://data/database.db
